### ISSUE TITLE
Please open new branch

### ISSUE THREAD

**Issue by DomThePorcupine** [AlexKDawson/HermesIM#2]
Hey Alex I was wondering if you could make a new dev branch for me to dump some canges in. thanks!

**Comment by AlexKDawson** [comment]
Done!

**Comment by AlexKDawson** [comment]
Do you just want to be added as a collaborator??

**Comment by DomThePorcupine** [comment]
You did that already. Closing

**Comment by AlexKDawson** [comment]
I did it last night, figured it would be easier.
